export default {
  document: '&document',
  topLeftOuter: '.one',
  topLeftInner: '.ten',
  topMiddleOuter: '.two',
  topMiddleInner: '.eleven',
  topRightOuter: '.three',
  topRightInner: '.twelve',
  midLeftOuter: '.four',
  midLeftInner: '.thirteen',
  midMiddleOuter: '.five',
  midMiddleInner: '.fourteen',
  midRightOuter: '.six',
  midRightInner: '.fifteen',
  bottomLeftOuter: '.seven',
  bottomLeftInner: '.sixteen',
  bottomMiddleOuter: '.eight',
  bottomMiddleInner: '.seventeen',
  bottomRightOuter: '.nine',
};
